### ISSUE TITLE
Compatibility with graphql-codegen

### ISSUE THREAD

**Issue by robertherber** [gqty-dev/gqty#104]
I'm using graphql-codegen for generating resolvers on the backend - and just introduced gqty for implementing tests in the same backend. I find it super convenient not having to specify queries - so thanks for this! 👍

With graphql-codegen I'm using the [mongodb plugin](https://www.graphql-code-generator.com/docs/plugins/typescript-mongodb) which among other things injects directives in the schema (`@entity`, `@column` etc). To get the gqty codegen working I added these explicitly additionally to my schema file (a fugly solution from a maintenance perspective) and it broke with the latest version `@graphql-tools/merge@8.1.2` version which doesn't want to merge my explicitly added directives with the ones the mongodb plugin adds (when running graphql-codegen).

Overall I think it'd be nice if gqty aligned more with graphql-codegen - maybe it could even be a plugin?

A few ideas I've tried:
- Creating a separate schema file for gqty generation with an import on top, like: `# import "./base-schema.graphql"` (doesn't seem to have any effect at all)
- Using `preImport` option to add content to the top of the schema. But from what I understand this is for adding to the TypeScript output. Maybe another option for prepending custom GraphQL schema content would be nice?
-  My current workaround is locking `@graphql-tools/merge` at 8.1.1, while keeping the extra directives in the schema file.

Any better suggestions on how to work around this?

**Comment by PabloSzx** [comment]
I don't understand what is the relation you want gqty to have with the directives you mention, both are completely unrelated, gqty is only consumption of an existing graphql API, and the directives for the mongodb plugin are only for the development of the API

**Comment by robertherber** [comment]
I simply want to be able to use a single schema to generate types for both resolvers and entities (with GraphQL-codegen) and gqty. For gqty to be able to parse my schema I need to add the directive definitions the MongoDB plugin adds - otherwise gqty fails to generate.

As I mentioned before there are a few ways to allow flexibility in these kinds of cases (neither are specific to my case - but a general solution that will help for similar schema issues):
- Allowing import statements: `# import "./base-schema.graphql"`
- Adding something similar to `preImport` that appends text to the schema file before processing
- Making the gqty fully compatible with graphql-codegen by adding it as a plugin

**Comment by PabloSzx** [comment]
You can use the programmatic API https://gqty.dev/docs/cli/programmatic to generate the gqty stuff with a specific graphql schema, where you can add whatever you want to the schema, using "writeGenerate" or "generate"

**Comment by robertherber** [comment]
Thanks! I'll check it out. Any possibility of adding this as an option/config to the CLI?

**Comment by PabloSzx** [comment]
> Thanks! I'll check it out. Any possibility of adding this as an option/config to the CLI?

I don't think so, that is the programmatic API exists, it's as easy to use as it can be, and almost every option fallbacks to the config file just as the CLI does
