### ISSUE TITLE
resolved only throws and error if selectFields is used

### ISSUE THREAD

**Issue by vd84** [gqty-dev/gqty#1075]
When using resolved, I seem to have to wrap the query with selectFields in order to catch an error if there is any network related error when executing the request. 

this is what I want to do
`  let userData
  resolved(() => {
    userData = query.user
  }).catch((err) => {
    setErrorMessage("error")
  })`

this is what I have to do
`  let userData
  resolved(() => {
    userData = selectFields(query.user)
  }).catch((err) => {
    setErrorMessage("error")
  })`

when I do it as  I want to, there is no error caught

**Comment by vicary** [comment]
@vd84 this should be covered in our tests, would you please share a minimum repo?

**Comment by vicary** [comment]
Please feel free to reopen when you are ready to share more context!
