### ISSUE TITLE
Put error property on query.$state object that's returned by useQuery

### ISSUE THREAD

**Issue by tylermichael** [gqty-dev/gqty#111]
Firstly, this library is amazing and thank you so much for building it!

I'm trying to work through error handling in my application and found that dealing with errors from gqty can be awkward.

I found that you can pass a function to your query like this, and then perhaps capture the error and then do something with it.
```tsx
const [error,setError] = useState<GQtyError>();
const query = useQuery({
    onError(e){
        setError(e);
    }
});

    
if (query.$state.isLoading) {
    return <p>Loading...</p>;
}

if(error){
    return <p>{error.message}</p>
}

return <p>{query.helloWorld}</p>
```

I find this awkward because anytime I want to capture an error, I have to copy and paste that kind of code or I suppose I could make a wrapper of some kind to expose this kind of functionality in a reusable way.

I really like how the other query methods work because they directly return multiple variables (data, error, isLoading). Returning these variables makes using them with React and its render loop a breeze. As my application progresses, I think I will start to use the more advanced query functions because they seem to have other useful features I might need.

As a (seemingly) straight forward way to address this though, what do you think about adding an error property to the `$state` object? This brings this query method a little bit more in line with how the other ones work and makes the above code more straight forward:

```tsx
const query = useQuery();

if (query.$state.isLoading) {
    return <p>Loading...</p>;
}

if(query.$state.error){
    return <p>{query.$state.error.message}</p>
}

return <p>{query.helloWorld}</p>
```

**Comment by PabloSzx** [comment]
You are correct, having an "error" property in the $state property is convenient, it will mean a couple of changes and is not as straight forward like a couple lines of code, but is possible, will work on it 👍

**Comment by felquis** [comment]
On previous version of gqless `query.$state.error` worked. For some reason it stopped working.
