### ISSUE TITLE
Using `resolved` or `inlineResolved` in Next.js `getStaticProps` does not revalidate

### ISSUE THREAD

**Issue by theodesp** [gqty-dev/gqty#1134]
Related:
https://github.com/wpengine/faustjs/issues/1038

We are using `inlineResolved` or `resolved` within Next.js `getStaticProps` and trying to invalidate the invalidate the data using the [revalidate](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration) property always returns the cached data.

For example:

```
import { getNextStaticProps } from "@faustjs/next";
import { client, PostIdType } from "client";
import { GetStaticPropsContext } from "next";

export default function Page(prop) {
  return <>Post ID: {prop.post.id}</>;
}

export async function getStaticProps(context: GetStaticPropsContext) {
  const { postSlug } = context.params;
  const post = await client.client.inlineResolved(() => {
    const query = client.client.query.post({
      id: postSlug as string,
      idType: PostIdType.SLUG,
    });
   return {
      id: postQuery.id,
      title: postQuery.title(),
    }
  });

  return getNextStaticProps(context, {
    Page,
    client,
    props: {
      post,
    },
    revalidate: 10,
  });
}

export function getStaticPaths() {
  return {
    paths: [],
    fallback: "blocking",
  };
}
```

When we update the page after 10 seconds we don't see any new changes. 

For example We changed the title of the post to `"Hello"` instead of `'Hello world!!' `and we still see the old `"Hello world!!"` title:

This should not work like that as Next.js ISR attempts to invalidate the data for that page after 10 seconds.

Here is the log for the requests even after the update the title stays the same:

```
{ post: { id: 'cG9zdDox', title: 'Hello world!!' } }
{
  __CLIENT_CACHE_PROP: '{}',
  __AUTH_CLIENT_CACHE_PROP: '{}',
  post: { id: 'cG9zdDox', title: 'Hello world!!' }
}
{ post: { id: 'cG9zdDox', title: 'Hello world!!' } }
{
  __CLIENT_CACHE_PROP: '{}',
  __AUTH_CLIENT_CACHE_PROP: '{}',
  post: { id: 'cG9zdDox', title: 'Hello world!!' }
}
{ post: { id: 'cG9zdDox', title: 'Hello world!!' } }
{
  __CLIENT_CACHE_PROP: '{}',
  __AUTH_CLIENT_CACHE_PROP: '{}',
  post: { id: 'cG9zdDox', title: 'Hello world!!' }
}
```

**Comment by PabloSzx** [comment]
gqty cache isn't revalidated automatically and Next.js doesn't communicate with it in any way, and the default behavior of `resolved` and `inlineResolved` is to read from cache.

add `{ refetch: true }` in the second parameter of `inlineResolved`

**Comment by vicary** [comment]
@theodesp please reopen and add more context if you think it's still a problem.
