### ISSUE TITLE
Basic Query

### ISSUE THREAD

**Issue by Jason-zyshen** [gqty-dev/gqty#1142]
I was trying to use test the basic query function, but it didn't work. Could you help me point out my mistake? I'm using the open-sourced graphql endpoint SpaceX. Thank you so much!

./pages/test.js
``` javascript
import { useQuery } from '../gqty';

const Test = () => {
  const query = useQuery({
    suspense: false,
    staleWhileRevalidate: true,
    onError(error) {},
  });

  if (query.$state.isLoading) {
    return <p>Loading...</p>;
  }

  return <p>{query.company.ceo}</p>;
}

export default Test
```

./gqty.config.cjs
``` javascript
/**
 * @type {import("@gqty/cli").GQtyConfig}
 */
const config = {
  react: true,
  scalarTypes: { DateTime: "string" },
  introspection: {
    endpoint: "https://api.spacex.land/graphql/",
    headers: {},
  },
  destination: "./gqty/index.ts",
  subscriptions: false,
  javascriptOutput: false,
  enumsAsConst: false,
}

module.exports = config
```

**Comment by Jason-zyshen** [comment]
I fixed it. It turns out that I should manually add the endpoint URL to the ./gqty/index.js file. 
I really hope this URL can be auto-generated from the config since they are usually the same. And it will make the entire workflow really smooth.

**Comment by vicary** [comment]
@Jason-zyshen If you didn't specify an endpoint, `gqty generate` should use your introspection endpoint by default. Would you mind sharing your gqty config?

**Comment by vicary** [comment]
@Jason-zyshen Feel free to reopen when you have time to update us with more context.
