### ISSUE TITLE
Updating the cache after the mutation

### ISSUE THREAD

**Issue by nemonemi** [gqty-dev/gqty#119]
Hi guys,
First of all, I'm still using the latest gqless because gqty was failing when I tried it, but that's another topic.
I wanted to know how you would solve the issue of having a query that resolves to a list, then updating it after one of its parts was changed. E.g.:
```
query {
  todos: [Todo!]!
  todo(id: ID!): Todo!
}
mutation {
  updateTodo(id: ID!, input: TodoData!): Todo!
}
```

Right now I'm trying the `refetchQueries: [query.todos]` and `awaitRefetchQueries: true`, but it doesn't work as expected.

Is there a way to efficiently update the cache of the `todos` after a `todo` was changed?

p.s. I've seen a method `setCache` in the docs, but I'm not sure how one would use it.

**Comment by PabloSzx** [comment]
> First of all, I'm still using the latest gqless because gqty was failing when I tried it, but that's another topic.

Can you explain what is the issue? if it's because of create-react-app using webpack 4, nothing to be done until create-react-app releases v5 with webpack 5, which is supposed to happen soon, an react-script@next using webpack 5 is already available



> I wanted to know how you would solve the issue of having a query that resolves to a list, then updating it after one of its parts was changed. E.g.:

You can mutate the proxies and the cache is going to be updated, or you can simply do "refetch(query.todos)"

> Right now I'm trying the `refetchQueries: [query.todos]` and `awaitRefetchQueries: true`, but it doesn't work as expected.
> 

can you explain what is the issue?

**Comment by nemonemi** [comment]
@PabloSzx ,
https://github.com/gqty-dev/gqty/issues/155

I will test it together with the GQTY, once I manage to get it working.

**Comment by felquis** [comment]
I always do this:

```js
const updatedData = mutation.updateCertificate({ id, input });

return {...updatedData}
```

**Comment by nemonemi** [comment]
I'm closing this because I'm no longer using this library. 
If anyone else experiences this problem, feel free to re-open it.
