### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by mmailaender** [gqty-dev/gqty#1263]
Firstly: I felt in love with GQty it's simply amazing what you're building here. I can feel already how much time this project can save developers! So keep up the great work 🚀 

After playing some time around with GQty I see some potential for the Docs to make it easier for newcomers to get into it.

## Query Code Completion
>I think this chapter could be helpful for everyone, that is not that experienced, because at least VSCode was in my case not smart enough to get Code Completion intuitive working depending on the GraphQL type - Maybe there is also an intellisense plugin available that makes the following obsolete? 🤔

Depending on the GraphQL Query Type, the code completion works different:

### Object, String, Number, Enum, ID etc.
**GraphQL Type Definition**
```tsx
export interface Query {
  currentUser: AuthResult;
}

export interface AuthResult {
  user?: Maybe<User>;
  error?: Maybe<ScalarsEnums['String']>;
}

export interface User {
  id: ScalarsEnums['ID'];
  name?: Maybe<ScalarsEnums['String']>;
  role: ScalarsEnums['UserRole'];
  email: ScalarsEnums['String'];
}
```

**Code Completion**
```tsx
// Get currentUser Object
query.currentUser

// Get name as String from currentUser
query.currentUser.user.name
```

### Function
**GraphQL Type Definition**
```tsx
export interface Query {
  publicPosts: (args: { input: CursorConnectionArgs }) => PostsConnection;
}
```

**Code Completion**
```tsx
// () needed
query.publicPosts()

```

#### GraphQL Type Definition
```tsx
export interface Query {
  
  // Array Object
  postsCategories: Array<Category>;

  // Function with Array
  namesList: (args?: {
    n?: Maybe<Scalars['Int']>;
  }) => Array<ScalarsEnums['String']>;
}

export interface Category {
  name?: Maybe<ScalarsEnums['String']>;
}
```

#### Code Completion
```tsx
// Array
query.postsCategories.map(category => category.name)

// Array Function
query.namesList().map(name => name)

```

## Configuring Codegen and queryFetcher

You explain how to set up codegen with GraphQL endpoint and authentication, but I was missing the clear point, that I have also to configure the **full path** and **authorization** again in `queryFetcher` in `gqty/index.ts`. Took me some time to debug that. 🙈 

So maybe you can extend the `Getting started` also with this information. Or maybe even better, centralizing the API and Authorization part. So that I have only one file where I set it up.

## Auto complete usefulness
>This one is probably again a good hint for people that are not living everyday in their IDE, or for beginners

![image](https://user-images.githubusercontent.com/87228994/202157912-3f2bb3e7-13fc-4a87-b563-d51985bb11a0.png)
![image](https://user-images.githubusercontent.com/87228994/202157981-e47d7fe2-264e-4941-8af5-32510b775159.png)

The two pictures are showing, how the auto complete is looking like for me (VSCode)

So while typing I can't see, that `data` is an `Array`. And I only see partially the rest of the return type. 
After reading about the tab complete feature, I was learning, that pressing `ctrl + space` again (while I'm in the tab completion menu) is showing me a long version. 💯  If this information could be placed in the `Getting started` or dedicated `Prepare IDE` page, this could probably make the start even smoother, especially because the auto complete is one major benefit of your solution.

A `Prepare IDE` section could maybe make sense if there are maybe also good Plugins that should be installed to get the most out of GQty like e.g. IntelliSense that helps to read the information easier in the info section, e.g. Data types has specific colors - Don't know if something like that is existing - at least not found something.

**Comment by vicary** [comment]
@mmailaender There are multiple conflicting ideas for the current website and some of them are not trivial, I prefer starting with minimal changes.

I have an idea of embedding an editor at the landing page, where it shows a preview of the resulting GraphQL query when you edit the code. Including arrays and query inputs there could be a start.

Let me know if this is enough, or instead you would prefer a dedicated document section.

## Fetcher URL and auth

That also caught me back at the start. Defaulting to introspection configs would be a more sensible way to initialize a project. I'll add that into my list.

## IDE type hints

I wonder if we can do anything about it, because IDE will always truncate when you have long field names.

It is possible to replace `[]` at the end with `Array<T>` so you recognize the array type right away. But speaking with my experience, the more I work on the same API, the less I would want the prefix `Array<` to get in my way. I would want the actual type instead.

What do you think?

**Comment by mmailaender** [comment]
## Query Code Completion

I think solving it with an intuitive editor at the landing page sounds good to me.

## IDE type hints

I think if I have a simple API, I would agree. For me, one of the huge benefits of GraphQL is dealing with big data. So having e.g. one unified API like [Netlifies OneGraph](https://www.onegraph.com/) or Apollo Federation. With that, I have most of the time probably a Schema area that is quite familiar to me and other areas that I use only sometimes or once. For that, having the array information is I think quite helpful.

Is it possible to define, the way how the data will be displayed through intellisense?
E.g. I like the GraphQL Schema way of declaring data types - It's quite compact:
**Scalar:** String
**Array:** [String]
**Mandatory:** String!
**Array & Mandatory:** [String]!

With colors, it could become even easier to read
![image](https://user-images.githubusercontent.com/87228994/207055095-73920ac1-a021-4eb7-90d4-66c1c0cf0949.png)

**Comment by vicary** [comment]
@mmailaender For the `[String]` pattern, unfortunately, TypeScript 4.9 thinks it is a kind of monad of a single element array. It could affect earlier versions but I haven't checked yet. This is one of the pending issues that I have to fix soon.

So if we want the most accurate type generated, it could either be `Array<String>` or `String[]`, but not `[String]`.

**Comment by vicary** [comment]
@mmailaender You may be interested in playing with the live editor in the preview deployments here https://github.com/gqty-dev/gqty/pull/1411
