### ISSUE TITLE
fetchOptions of queryFetcher is undefined

### ISSUE THREAD

**Issue by mmmoli** [gqty-dev/gqty#1300]
Hi, really excited by gqtv.

I'm using the JS client in a Next.js app.
The `fetchOptions` are always undefined.

Here's my `resolved` call:

```
return await resolved(() => query.projects(), {
    fetchOptions: {
        headers: {
            'Content-Type': 'application/json',
             authorization: 'secret_token',
        },
        signal: controller.signal,
   },
});
```
    
And the stock queryFetcher:

```
const queryFetcher: QueryFetcher = async function (
  query,
  variables,
  fetchOptions
) {
  debugger; // fetchOptions is always undefined
  …
}
```
I'd expect to see `authorization: 'secret_token',`.

Deps:
- "@gqty/logger": "3.0.0-alpha-c5b89dbd.0",
-  "@gqty/react": "2.2.0-alpha-445c0456.0",
- "@gqty/subscriptions": "3.0.0-alpha-c5b89dbd.0",
- "gqty": "2.4.0-alpha-c5b89dbd.0",

DevDeps:
- "@gqty/cli": "3.3.1-alpha-c5b89dbd.0",
    
Tried previous versions too.

Anything you'd like me to investigate?

**Comment by vicary** [comment]
Using a fresh install with the exact alpha versions, I can see my supplied `fetchOptions` from a simple `console.log()`.

Would you mind sharing a minimum repo? No need to share your schema, your generated client in a Codesandbox should do.

**Comment by vicary** [comment]
@mmmoli Please feel free to reopen when you are ready to share more context!
