### ISSUE TITLE
Generate string literals instead of enums

### ISSUE THREAD

**Issue by mmkal** [gqty-dev/gqty#1441]
Hi! Big fan this library. One thing I'd like to configure but can't find in the docs is switching the enums used for inputs to string literals. Our team don't use enums in typescript at all, we find there isn't really value in them given you can achieve the same type safety by using string literals, without having to import something extra, and without having any ambiguity about how typescript will compile to js.

So basically it'd be great to change the generate type for this example input type:

```ts
export enum IssueState {
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
}

/** Filter by IssueState */
export interface IssueStateInput {
  eq: IssueState
}
```

To:

```ts
export type IssueState = 'CLOSED' | 'OPEN'

/** Filter by IssueState */
export interface IssueStateInput {
  eq: IssueState
}
```

I _think_ at runtime they'd be identical, but no need to import anything extra to specify an `IssueState`.

**Comment by vicary** [comment]
We have an option `enumsAsStrings` in `gqty.config.js`, you may try that.

**Comment by vicary** [comment]
@mmkal Feel free to reopen if the option above doesn't work.

**Comment by mmkal** [comment]
Perfect, thank you! Not sure how I didn't find that in the docs. Actually `enumsAsConst` is even better, since it allows for either usage.
