### ISSUE TITLE
[BUG] npm ERR! Unsupported URL Type "link:": link:/Users/vicary/Documents/Projects/vicary/multidict

### ISSUE THREAD

**Issue by LasseRosenow** [gqty-dev/gqty#1586]
When running `npm install gqty` I get this error:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:/Users/vicary/Documents/Projects/vicary/multidict

npm ERR! A complete log of this run can be found in:
```

It seems to be caused by the `multidict` dependency, which uses a `link:` prefix inside its package.json which is not supported anymore?

For additional information see: [stackoverflow](https://stackoverflow.com/questions/74679689/unsupported-url-type-link-while-using-npm)

**Comment by vicary** [comment]
@LasseRosenow fixed in `4.0.0-alpha-8054dbb3.0`, would you please try again?

The repo is depending on a legacy pipeline which releases the alpha channel as latest, we are already working on it.
