### ISSUE TITLE
Ability to use a Local .graphql File Instead of Introspection

### ISSUE THREAD

**Issue by jrkienle** [gqty-dev/gqty#1587]
Hey all!

First off, this seems like an amazing idea so far, I'm loving how intuitive everything is. My only issue is that my current setup requires the schema to be generated from a local `.graphql` file instead of introspected from a URL. I haven't found any documentation on how to do this, and my (although limited) poking around in the codebase hasn't yielded any results either. Is there a plan to add support (or any current support) for generating things based off of a `.graphql` file like how [GraphQL Codegen](https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#configuration-options) does?

**Comment by jrkienle** [comment]
Nevermind I'm an actual moron

**Comment by vicary** [comment]
@jrkienle Come join our Discord server, you may ask more casual questions there as you try GQty!
