### ISSUE TITLE
Module '"gqty"' has no exported member 'Cache'

### ISSUE THREAD

**Issue by mmkal** [gqty-dev/gqty#1593]
I got this typescript error right after running `npx @gqty/cli`. No `gqty` was installed, so installed the latest one, which has the same sha in it as the CLI. Not sure which one I'm supposed to do though? Could the CLI be updated to at least print out what version should be used?

package.json

```
"dependencies": {
    "gqty": "3.0.0-alpha-e9f8f97b.0",
    "@gqty/cli": "4.0.0-alpha-e9f8f97b.0"
}
```

**Comment by mmkal** [comment]
Ah, this was a vscode caching issue. I'm going to close, although some more info on which `@gqty/cli` versions work with which `gqty` versions would be nice.

**Comment by vicary** [comment]
@mmkal We can definitely add a minimum version check for `gqty` and `@gqty/*` in the new CLI, it should also prompt for an automatic installation if they doesn't match. Thanks for the feedback!
