### ISSUE TITLE
 No selections found. If you are reading from the global accessors, try using the first argument instead. 

### ISSUE THREAD

**Issue by fasibio** [gqty-dev/gqty#1611]
I have some trouble with v3 $refetch... 

I get the error  
```
No selections found. If you are reading from the global accessors, try using the first argument instead. 
```
But i didn´t find what it means or how can i solve it. 

How ever if i call ```$refetch(true)``` this message is shown and nothing happens. 

Thank you for your help. 

Version: 3.0.0-alpha-7b21563c.0
React: true

**Comment by vicary** [comment]
It usually means you are using the V2 way `import { query } from "gqty";`

In V3 these should be used instead:
1. `const query = useQuery();` in React, and 
2. `resove(({ query }) => { ... });` in core.

**Comment by fasibio** [comment]
So the documentation. is wrong ? 
https://gqty.dev/guides/react/read

i changed it like this but nothing changed... 

at a second example he miss the array entity by refresh. 
Inizial it execute. But after call refresh(true), it execute and an entity (from type array) is not longer a part of the query.

**Comment by vicary** [comment]
Do you mean the sub-selections under an array is missing when you call `$refresh(true)`?

**Comment by vicary** [comment]
@fasibio I'd like to reproduce the issue, please share more info when available!

**Comment by vicary** [comment]
Please reopen if this issue still exists.
