### ISSUE TITLE
ESM-only prettier plugins break @gqty/cli

### ISSUE THREAD

**Issue by paolo-rossig** [gqty-dev/gqty#1626]
If you use a ESM-only prettier plugin, such us `prettier-plugin-tailwindcss`, the `codegen.mjs` will throw the following error:

Error [ERR_REQUIRE_ESM]: require() of ES Module .../prettier.config.js from .../node_modules/@gqty/cli/deps.js not supported.

Based on this [issue](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/207#issuecomment-1698071122), this plugin can not be loaded with require or import, just put it in the `prettier.config.js` file like this:

```js
const config = {
  semi: false,
  singleQuote: true,
  plugins: ['prettier-plugin-tailwindcss']
}
export default config
```
Currently using:
`"@gqty/cli": "4.0.0-alpha-7b21563c.0",`

**Comment by vicary** [comment]
We have a thread in Discord about a similar issue, which the op found a workaround.
Would you mind heading there to see if it's the same case?

https://discord.com/channels/874477141834739762/1200868810434039939

**Comment by vicary** [comment]
Please feel free to reopen if the issue persists.
