### ISSUE TITLE
If null is returned in useMutation, the entire response is returned

### ISSUE THREAD

**Issue by narumincho** [gqty-dev/gqty#1991]
```tsx
const Login = () => {
  const [mutation, { data }] = useMutation((mutation) => {
    return mutation.post;
  });

  console.log(data);

  useEffect(() => {
    mutation();
  }, [mutation]);

  return <div>{data}</div>;
};
```

```gql
type Mutation = {
  # always return null
  post: String
}
```

## expected log
```
undefined
null
```

## actual log
```
undefined
{ mutation: { post: null } }
```

## If you change Mutation.post to return "abc" instead of null ( expected and actual )
```
undefined
abc
```

**Comment by vicary** [comment]
@narumincho Please try `gqty@3.2.1` and see if it fixes the issue.

`null` is now allowed, while `undefined` will still return all selections made inside the function.

**Comment by narumincho** [comment]
I have confirmed that it has been fixed. Thank you for your quick response!
