### ISSUE TITLE
bug: Union requests with `map` seem to fail on Server Side

### ISSUE THREAD

**Issue by blakewilson** [gqty-dev/gqty#276]
When doing an `$on` Union request mapping over an array seems to not work as intended server side.

Ideally, the example should produce a query such as:

```graphql
query MyQuery {
  page(id: "2", idType: DATABASE_ID) {
    id
    blocks {
      name
      ... on CoreParagraphBlock {
        originalContent
      }
    }
  }
}
```

However, this is not the intended result. The result is two queries, one which is executed server side, and the other client side.

I have a reproducable working repo here with examples: https://github.com/blakewilson/gqty-on-ssg-next-issue

## Steps to Reproduce

1. `npm run build`
2. `npm run start`
3. Navigate to `localhost:3000`
4. Notice the CSR `/graphql` network request

Notice that by doing something like `blocks[0]?.$on.CoreParagraphBlock?.originalContent` works as expected, the data is set in the `cacheSnapshot`.

**Comment by PabloSzx** [comment]
The example given has an error, putting a data selection behind a condition, for server-side rendering (and for preventing cascade requests, aka doing two or more requests for the same component) all the selections have to be made before doing any conditional using the data, basically changing from:

```tsx
// WRONG: Conditional selection behind conditional
{blocks.map((block, index) => {
        switch (block.name) {
          case "core/paragraph": {
            return (
              <div
                key={index}
                dangerouslySetInnerHTML={{
                  __html: block?.$on.CoreParagraphBlock?.originalContent,
                }}
              />
            );
          }
        }
      })}
```

```tsx
// Requiring the data selection
{blocks.map((block, index) => {
        const originalContent = block?.$on.CoreParagraphBlock?.originalContent;
        switch (block.name) {
          case "core/paragraph": {
            return (
              <div
                key={index}
                dangerouslySetInnerHTML={{
                  __html: originalContent,
                }}
              />
            );
          }
        }
      })}
```
