### ISSUE TITLE
Prevent infinit loops on gqty query object with circular references

### ISSUE THREAD

**Issue by Lappihuan** [gqty-dev/gqty#283]
With tools like the React or Vue devtools accessing the components data it can crash if there is circular references.

To prevent this, a max recursion depth parameter should be added to the core client config, aswell as a default value of maybe 10.
Once the limit is reached the gqty query object will stop and return null, preventing a infinite loop.

**Comment by PabloSzx** [comment]
Fixed in [gqty@2.1.0](https://github.com/gqty-dev/gqty/releases/tag/gqty%402.1.0) :tada:
