### ISSUE TITLE
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by cdreier** [gqty-dev/gqty#309]
Hi,

i just switched from gqless to gqty and ran in a few issues: (everything tested with a fresh create-react-app typescript template)

One small issue: i think the docs are missing, that you need to install `@gqty/react` 

After everything was setup correctly, i ran in the error in the title

```
Failed to compile.

./node_modules/@gqty/react/query/hoc.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
```

I also searched a bit, and as far as i can see, there are issues with webpack and mjs modules?

Thanks a lot for your work and your help!

Regards,
Christian

**Comment by cdreier** [comment]
sidenote: gqless in the latest version hase issues with graphql v16.x.x - we tested gqty with both, graphql v16 and v15 - and the issue is still the same

**Comment by PabloSzx** [comment]
Use webpack 5, not webpack 4

**Comment by cdreier** [comment]
Hi, thanks for your fast response!

for some reason i assumed, that create-react-app is maintained :/

just tested it with snowpack and everything worked just fine - so i think we can close this issue

thanks a lot for your effort in gqless / gqty, this is just awesome!

**Comment by pedromaprovadig** [comment]
I used a alpha version as a workaround to this problem:

https://github.com/facebook/create-react-app/discussions/11278
