### ISSUE TITLE
Infinite loop when mapping unions

### ISSUE THREAD

**Issue by nemonemi** [gqty-dev/gqty#314]
@PabloSzx,
I am experiencing this problem with the gqty:2.1.0.

I am mapping properties where there's a union. I want to have an ID mapped for both of them.

    const properties = certificateResult.$on.Certificate.properties.map((config) => ({
      // This does not cause an inifinite loop
      id: config?.$on.CertificatePropertySimple?.property.id,

      // This causes an infinite loop
      id: (config?.$on.CertificatePropertySimple || config?.$on.CertificatePropertyDate)?.property.id

      // This as well
      id: config?.__typename === 'CertificatePropertySimple'
          ? config?.$on.CertificatePropertySimple?.property.id
          : config?.$on.CertificatePropertyDate?.property.id,
    }));

    return <div>{properties[1]?.id}</div>;
It prints out the ID, but still causes an infinite loop. Why is that, and how to prevent it?

This sounds similar to me as this other already closed issue https://github.com/gqty-dev/gqty/issues/236

**Update:**
I have tried accessing the data directly, without any mapping, and with the first part of the union it works like a charm, but with the second one, it causes the infinite loop.

```ts
// This works
return <div>{certificateResult.$on.Certificate.properties[1]?.$on.CertificatePropertySimple?.property.id}</div>
```

```ts
// However, accessing the second union part causes the infinite loop
return <div>{certificateResult.$on.Certificate.properties[0]?.$on.CertificatePropertyDate?.property.id}</div>
```

```ts
// This is how the properties array looks like, should the indexes on the properties cause any confusion
certificateResult.$on.Certificate.properties === [
// 0. $on.CertificatePropertyDate
// 1. $on.CertificatePropertySimple
]
```

**Update 2:**
The problem I believe is that the library doesn't resolve the cache very well, thus always things it needs to fetch more to complete it.

**Comment by nemonemi** [comment]
I'm closing this because I'm no longer using this library. 
If anyone else experiences this problem, feel free to re-open it.

**Comment by cdaringe** [comment]
I also get an infinite loop when trying to access some values:

```jsx
      <pre>
        {query.allMfes().edges?.map((e) => {
          return e.node.version;
        })}
      </pre>
```

If i drop the `.version` (or any other field access off of `e.node`), the infinite loop halts, but of course react cannot render a that object.

The infinite loop of API calls also does re-trigger the loading state. I think the cache resolve suggestion above is correct, as my queries _do_ have the full data present!

**Comment by PabloSzx** [comment]
> I also get an infinite loop when trying to access some values:
> 
> ```js
>       <pre>
>         {query.allMfes().edges?.map((e) => {
>           return e.node.version;
>         })}
>       </pre>
> ```
> 
> If i drop the `.version` (or any other field access off of `e.node`), the infinite loop halts, but of course react cannot render a that object (the proxy?).
> 
> The infinite loop of API calls also does re-trigger the loading state. I think the cache resolve suggestion above is correct, as my queries _do_ have the full data present!
> 
> Inspection revealed the following. There is a for loop, processing lookup selections. The `key` generated is not in the cache. The key also is _not_ representative of the query i authored--there is a `0` suffixed onto it. Thus, though the cache is **fully hydrated** with correct data, the `Selection` lookup fails, due to this wrong key:
> 
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/1003261/148637855-c63b84ac-9c0d-4bd9-a2ba-bd8a3cf5fd04.png">

this is not related to the union logic, it has to be a new issue with a reproduction
