### ISSUE TITLE
Is there a way to pass a custom fetch to the resolved or query function?

### ISSUE THREAD

**Issue by raymclee** [gqty-dev/gqty#328]
I'm trying to use gqty in sveltekit. It need to use the fetch provided by sveltekit to access server cookies.

**Comment by vicary** [comment]
You may modify the `queryFetcher` in your generated client, please move questions about general usages to Discord.

**Comment by raymclee** [comment]
> You may modify the `queryFetcher` in your generated client, please move questions about general usages to Discord.

Yes. I know we can modify the queryFetcher function but there is a custom fetch from sveltekit and It's coming from a load function on the page. I don't know how to pass it to queryFetcher?

```ts
<script context="module" lang="ts">
  import { query, resolved } from "$lib/gqty";
  import type { Load } from "@sveltejs/kit";

  export const load: Load = async ({ fetch }) => {
    let number = await resolved(() => query.double({ number: 20 }), {
      customFetch: fetch,
    });

    return {
      props: { number },
    };
  };
</script>
```

can we pass it to the resolved function like above example?

**Comment by vicary** [comment]
Then the topic goes to general JavaScript usage.

You may export or modify the `createClient` function to take in whatever implentation before you make your first call to `resolved()`.

This should really goes to Discord.
