### ISSUE TITLE
Document the usage of the `$on` property

### ISSUE THREAD

**Issue by blakewilson** [gqty-dev/gqty#342]
Documentation on the usage of the `$on` property would be helpful, as of right now the only syntax you can find on it is from past issues.

I can write up something for this.

**Comment by ttstauss** [comment]
Yes, some help on this property would be great. I find that it's spotty. It doesn't seem to always exist on some types (while working on others) even though it works perfectly fine in GraphiQL IDE.

As an example this GraphiQL query:
```
...
      ... on AcfStatsBlock {
        name
        attributes {
          ... on AcfStatsBlockAttributes {
            data
          }
        }
      }
...
```
Yields this data:
```
        {
          "name": "acf/stats",
          "attributes": {
            "data": "{\"stats\":[\"129\",\"130\",\"131\"],\"_stats\":\"field_623ccdc129ba0\"}"
          }
        },
```
But when trying to access it via the frontend I get an undefined error:
`TypeError: Cannot read properties of undefined (reading 'AcfStatsBlockAttributes')`

With this type error:
`Property '$on' does not exist on type 'AcfStatsBlockAttributes'.`

Without documentation I'm left wondering how to solve these types of issues (or why it works for some and not others).

**Comment by vicary** [comment]
I am cleaning up old issues.

Since V3 is merged you may want to check it out via `gqty@canary`, we also have new documentations for [interface and unions](https://gqty.dev/guides/react/read#interfaces-and-unions) should explains the usage.

Please reopen if the issue still exists in V3!
