### ISSUE TITLE
Can not generate config file

### ISSUE THREAD

**Issue by davidsoderberg** [gqty-dev/gqty#455]
Hi, when I try to follow get started I get:
```Named export 'print' not found. The requested module 'graphql' is a CommonJS module, which may not support all module.exports as named exports.```

Why do I get this?

**Comment by PabloSzx** [comment]
Version of Node.js?

**Comment by davidsoderberg** [comment]
I tried 14 and 16, non of them worked...

**Comment by PabloSzx** [comment]
just tested with Node 16.13.1, 14.18.2 and 12.22.8 and worked as expected

**Comment by PabloSzx** [comment]
oh well, the most important thing I forgot, what version of GraphQL you have installed

**Comment by PabloSzx** [comment]
well, anyways, for gqty/cli@3.0.1 all the external imports are going to be "import * as" to prevent esm<-> cjs interop issues like this, but if the graphql version is incompatible it's going to fail anyways

**Comment by fasibio** [comment]
@PabloSzx 
perhaps is a good idea to add the supported graphql version the documentation 
i used a fresh installed version and get the error with "@gqty/cli": "3.0.1"
"graphql": "^16.2.0",
`
import { print } from 'graphql';
         ^^^^^
SyntaxError: Named export 'print' not found. The requested module 'graphql' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'graphql';
const { print } = pkg;

`
So the import is allmost there: 
@gqty/cli/introspection.mjs:1
`import { print } from 'graphql';`

Where is my missconfiguration ? 


I use Vite
