### ISSUE TITLE
Will this work with react-native? 

### ISSUE THREAD

**Issue by cmaycumber** [gqty-dev/gqty#48]
Will this library by any chance work with react-native out of the box? I'm not familiar with how the caching is handled and am curious if we could use this in our project, or if it would be possible to customize it to make it work.

**Comment by PabloSzx** [comment]
it should work, there isn't any browser-specific / react-dom feature being used, and it's already being used in React Native projects 👌

**Comment by PabloSzx** [comment]
what is the issue you are having, gqty doesn't use any browser-specific feature for it to be react-native incompatible

**Comment by johnsonjo4531** [comment]
Maybe this error from the catch of my fetch request will help... tomorrow I'll try to get together a minimum viable example. So, you can look into it further.

```sh
[Unhandled promise rejection: Error: undefined is not an object (evaluating 'executionResult.data')]
at http://packager.9n-xgc.anonymous.app.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:188376:293 in _createSuperInternal
at node_modules/gqty/Error/index.js:12:4 in GQtyError#constructor
at node_modules/gqty/Error/index.js:30:31 in GQtyError.create
at node_modules/gqty/Client/resolvers.js:318:22 in resolve
```
