### ISSUE TITLE
@gqty/cli npx compat?

### ISSUE THREAD

**Issue by jedahan** [gqty-dev/gqty#494]
Not sure what is needed, but it would be nice to try out the cli with something like: 

```shell
npx -p @gqty/cli gqty generate https://beta.pokeapi.co/graphql/v1beta
```

or

```shell
npx @gqty/cli -- generate https://beta.pokeapi.co/graphql/v1beta
```

**Comment by vicary** [comment]
It's already compatible, try `npx @gqty/cli generate https://graphql.anilist.co/`.
