### ISSUE TITLE
Question: Pagination & keyArgs

### ISSUE THREAD

**Issue by seanaguinaga** [gqty-dev/gqty#509]
Hello

How is pagination handled with this library?

Also

With Apollo I can use keyArgs: https://www.apollographql.com/docs/react/pagination/offset-based/#setting-keyargs-with-offsetlimitpagination to make sure lists of the same type don't combine themselves.

```
thread: offsetLimitPagination([
     "where",
     ["last_message", ["message_participants", ["_and"]]],
  ]),
```

**Comment by seanaguinaga** [comment]
I assume I will just have to replicate this manually based off of the docs

**Comment by PabloSzx** [comment]
all the pagination-specific features available are only within the React bindings through `usePaginatedQuery` https://gqty.dev/docs/react/fetching-data#usepaginatedquery which doesn't follow an opinionated way of doing it
