### ISSUE TITLE
Question: __typename optional?

### ISSUE THREAD

**Issue by cdaringe** [gqty-dev/gqty#512]
# Problem

My GQL API currently [does not support __typename on some thru nodes](https://github.com/supabase/pg_graphql/issues/24).

# Discussion

- `__typename` is being auto added by the api client
- is it required in all sections/edges of the query?

Thanks!

**Comment by PabloSzx** [comment]
It's automatically added because of normalization, which requires it, you can turn it off, which doesn't add `__typename`:

https://gqty.dev/docs/client/config#normalization

```ts
createClient<GeneratedSchema, SchemaObjectTypes, SchemaObjectTypesNames>({
  // ...
  normalization: false,
});
```

**Comment by cdaringe** [comment]
Wow, thanks! I searched around some, but managed to miss that in the docs
