### ISSUE TITLE
missing "subscription" type ("subscription" type name conflict)

### ISSUE THREAD

**Issue by lidorcg** [gqty-dev/gqty#575]
when I use the CLI to generate type for my schema, one specific type is missing: "subscription"

Here's subscription_aggregate exists but missing "subscription"

```ts
/**
 * aggregated selection of "subscription"
 */
export interface subscription_aggregate {
  __typename?: "subscription_aggregate";
  aggregate?: Maybe<subscription_aggregate_fields>;
  nodes: Array<subscription>;
}

```

This means the generated schema is broken from the get go :(

**Comment by lidorcg** [comment]
I'm suspecting some kind of collision with GraphQL's 'Subscription'

**Comment by lidorcg** [comment]
I ended up using @graphql-codegen with the same config as gqty and added `import {subscription} from ...` to `schema.generated.ts` which seems to have solve the problem.
Less than ideal however...

**Comment by vicary** [comment]
gqty uses `@graphql-codegen` under the hood with some transformations, e.g. queries with inputs into functions, you cannot use substitute with types generated with @graphql-codegen directly.

I have been using gqty's generated types for AppSync subscriptions and is having no problem so far.

Would you help us reproducing the issue? Please share a minimum reproducing copy of the followings,
1. Your introspection source (*.graphql or endpoint)
2. The version of gqty
3. Your gqty config
4. Your working config for `@graphql-codegen/typescript`

**Comment by lidorcg** [comment]
No problem whatever I can do to help this awesome tool :)

1. I have a `graphql.schema.json` produced by `@graphql-codegen` is it good enough? [graphql.schema.json.txt](https://github.com/gqty-dev/gqty/files/7950109/graphql.schema.json.txt)
2. `"gqty": "^2.1.0"`
3. gqty config:
```js
/**
 * @type {import("@gqty/cli").GQtyConfig}
 */
const config = {
  introspection: {
    endpoint: "http://localhost:8080/v1/graphql",
    headers: {
      "x-hasura-admin-secret": "password",
    },
  },
  destination: "./src/utils/gqty/index.ts",
  scalarTypes: {
    ID: "string",
    String: "string",
    Boolean: "boolean",
    Int: "number",
    Float: "number",
    bigint: "number",
    bpchar: "string",
    date: "string",
    json: "any",
    jsonb: "any",
    numeric: "number",
    smallint: "number",
    time: "string",
    timestamptz: "string",
    uuid: "string",
  },
  preImport: 'import { subscription } from "./graphql";', \\ this is my hack :)
  enumsAsStrings: true,
  subscriptions: false,
  react: false,
  javascriptOutput: false,
};

module.exports = config;
```
4. codegen config:
```js
module.exports = {
  schema: [
    {
      "http://localhost:8080/v1/graphql": {
        headers: {
          "x-hasura-admin-secret": "password",
        },
      },
    },
  ],
  overwrite: true,
  generates: {
    "./src/utils/gqty/graphql.ts": {
      plugins: [
        {
          typescript: {
            declarationKind: "interface",
            addUnderscoreToArgsType: true,
            scalars: {
              ID: "string",
              String: "string",
              Boolean: "boolean",
              Int: "number",
              Float: "number",
              bigint: "number",
              bpchar: "string",
              date: "string",
              json: "any",
              jsonb: "any",
              numeric: "number",
              smallint: "number",
              time: "string",
              timestamptz: "string",
              uuid: "string",
            },
            namingConvention: "keep",
            enumsAsTypes: true,
            allowEnumStringTypes: true,
          },
        },
        "typescript-operations",
      ],
      config: {
        skipTypename: false,
        withHooks: false,
        withHOC: false,
        withComponent: false,
      },
    },
    "./src/utils/gqty/graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
};
```

**Comment by lidorcg** [comment]
> I'm suspecting some kind of collision with GraphQL's 'Subscription'
> 
> BTW when I use @graphql-codegen it works fine, I have my subscription type. Is there an easy way to hook gqty with my generated types?

I did had a collision back then with a custom type: `Subscription` and ended up changing it's name (note: the missing type is `subscription` in lower case).

**Comment by PabloSzx** [comment]
> One more detail that might be relevant (not sure, just because it's that `subscription` again :): For some reason this specific snippet keeps complaining that: `[gqty] Warning! No data requested.`
> 
> ```ts
>   const subscription_id = await resolved(() => {
>     const { id } = mutation.insert_subscription_one({
>       object: {
>         user_id: userId,
>         bluesnap_plan_id: planId,
>         bluesnap_subscription_id: subscriptionId,
>       },
>     });
>     return id;
>   });
> 
>   console.log(subscription_id);
> ```
> 
> I've used this exact pattern (with different entities) in multiple places but here for some reason it breaks, on the console I get:
> 
> ```shell
> [gqty] Warning! No data requested.
> undefined
> ```
> 
> Switching to traditional gql client and query solved this problem but it's really curious.
> 
> I'm really not sure these are related issues, but that `subscription` is causing troubles all around laughing

The mutation require a `refetch: true` or `noCache: true` option, or you can use the `mutate` function helper that is exported by the client, which has automatically adds it, and it has the mutation object as parameter, instead of an empty object as the resolved function

**Comment by lidorcg** [comment]
```ts
const subscription_id = await mutate((mutation) => {
    const { id: subscription_id } = mutation.insert_subscription_one({
      object: {
        bluesnap_plan_id: String(planId),
        bluesnap_subscription_id: String(subscriptionId),
        user: {
          data: {
            is_premium: true,
          },
          on_conflict: {
            constraint: "user_pkey",
            update_columns: ["is_premium"],
            where: { id: { _eq: userId } },
          },
        },
      },
    });
    return subscription_id;
  });
```

still getting `[gqty] Warning! No data requested.` :cry:

**Comment by PabloSzx** [comment]
After transforming it into a schema.graphql file, which is the standard SDL of graphql, it can be easier to see that it seems to be a name conflict

schema.graphql: https://gist.github.com/PabloSzx/b37cb0db6f7c0e4a06db8ec4189f26f7


In gqty the type "subscription" is reserved, you cannot use it as a regular type that can be returned from a query/subscription

here you can see that "gqty" uses the "subscription" name for the "subscription_root" in this case

![image](https://user-images.githubusercontent.com/8672915/151727920-5c432584-391b-469d-8e77-738391e78298.png)

and the schema.graphql defines it as a regular type

![image](https://user-images.githubusercontent.com/8672915/151728024-6830af66-4eb6-4ba7-9d56-7bc43f573184.png)


there is no plan to fix this use case, using "subscription" as a not actual GraphQL subscription is a bad practice

**Comment by lidorcg** [comment]
> I'm suspecting some kind of collision with GraphQL's 'Subscription'
> 
> BTW when I use @graphql-codegen it works fine, I have my subscription type. Is there an easy way to hook gqty with my generated types?

Yes, exactly what I suspected...
Well, I found a workaround using `@graphql-codegen`,but will probably change the type's name eventually.
Thanks for the thorough investigation and concern for my issue, very much appreciated! :bow:
