### ISSUE TITLE
Feature Request - Add `credentials` support for introspect

### ISSUE THREAD

**Issue by Lonli-Lokli** [gqty-dev/gqty#689]
Currently there is no way to specify credentials for introspecting so request failing

https://github.com/gqty-dev/gqty/blob/main/packages/cli/src/introspection.ts#L40

**Comment by Lonli-Lokli** [comment]
I believe it can be added similar to https://github.com/gqty-dev/gqty/pull/640

**Comment by vicary** [comment]
@Lonli-Lokli You should be able add an `Authorization` header to the `introspection.headers` config, please reopen if a general credentials support is missing.

Let's discuss Kerberos specific authentication in #694.
