### ISSUE TITLE
Use `fetch` instead of `request` for introspection

### ISSUE THREAD

**Issue by Lonli-Lokli** [gqty-dev/gqty#694]
Related to https://github.com/gqty-dev/gqty/issues/689

Currently there is no possibility to do introspect for endpoints, protected by Kerberos

**Comment by vicary** [comment]
@Lonli-Lokli You should be able to fetch your access ticket with something like [`kerberos`](https://www.npmjs.com/package/kerberos) and put that into `introspection.headers.authorization` in your config file, it's just a JavaScript file.

I am not super familiar with Kerberos protected endpoints and the SPNEGO protocol, please reopen and further elaborate if the method above is not enough for your use case.
