### ISSUE TITLE
Can't access interface that exists from `$on` property in GQty

### ISSUE THREAD

**Issue by blakewilson** [gqty-dev/gqty#733]
Hey team. I'm experiencing an odd issue where I can not access an interface (`NodeWithTitle`) from the `$on` property in GQty. This interface exists, and I can query it via GraphiQL.

Works when querying the GraphQL API directly:
<img width="1600" alt="Screen Shot 2022-03-16 at 4 40 24 PM" src="https://user-images.githubusercontent.com/5946219/158696543-e62062e5-07ca-4c18-bf12-417799cfa023.png">

Not in GQty:
<img width="1950" alt="Screen Shot 2022-03-16 at 4 39 19 PM" src="https://user-images.githubusercontent.com/5946219/158697032-383c4b05-dc89-49d1-82b3-64c3a41410ec.png">

<img width="1600" alt="Screen Shot 2022-03-16 at 4 48 41 PM" src="https://user-images.githubusercontent.com/5946219/158697051-6a92f598-4c8b-42fc-ac0d-bc956a2558a3.png">

<img width="1600" alt="Screen Shot 2022-03-16 at 4 48 15 PM" src="https://user-images.githubusercontent.com/5946219/158697064-4008f5bb-4e73-4cc2-8f24-df4d8481ae80.png">

I have a minimal reproducible repo available here: https://github.com/blakewilson/gqty-on-interface-bug

Additionally, the GraphQL endpoint is available at https://blakewilson77.wpengine.com/graphql and public introspection is enabled for debugging purposes.

**Comment by ttstauss** [comment]
I have the same issue I mentioned on issue [342](https://github.com/gqty-dev/gqty/issues/342).

**Comment by vicary** [comment]
I am cleaning up old issues.

Since V3 is merged you may want to check it out via `gqty@canary`, please reopen if the issue still exists in V3!
