### ISSUE TITLE
lodash\mergeWith.js issue

### ISSUE THREAD

**Issue by scholtz** [gqty-dev/gqty#791]
Hi, anybody else receiving this issue when using typescript?

```[!] Error: 'default' is not exported by node_modules\lodash\mergeWith.js, imported by node_modules\gqty\Cache\dataCache.mjs```

its doing when i try to include gqty into the library

```
import { graphql } from './gqty';
console.log("graphql",graphql)`
```

before i do this the build works (tsc, rollup -c rollup.config.js )

**Comment by PabloSzx** [comment]
With #949 and the new @gqty/utils package this will be 100% fixed
