### ISSUE TITLE
Use customFetch for fetching the schema

### ISSUE THREAD

**Issue by ghoshnirmalya** [gqty-dev/gqty#827]
In the GraphQL Code Generator, there is an option to use `customFetch` to fetch the schema. Is it possible to use something similar in gqty?

**Comment by PabloSzx** [comment]
You can always do programmatic usage https://gqty.dev/docs/cli/programmatic

You can, for example, do the introspection with whatever logic you want, and just call `writeGenerate` with the introspected schema

**Comment by ghoshnirmalya** [comment]
Thank you.
