### ISSUE TITLE
If nothing is read from the result of the mutation, the mutation is not executed

### ISSUE THREAD

**Issue by vkrol** [gqty-dev/gqty#829]
# Problem
If nothing is read from the result of the mutation, the mutation is not executed. It's definitely a bug. This issue is the clone of https://github.com/samdenty/gqless/issues/186.

# Workarounds
The workaround is to read `__typename` or `affected_rows`.

**Comment by vicary** [comment]
This is a known issue and likely wontfix since this is how the underlying proxy trigger queries, including mutations.

You may try creating a PR to revise the core mechanism if you think it can be improved, closing this for now.
