### ISSUE TITLE
would this work with vuejs 3?

### ISSUE THREAD

**Issue by tintin10q** [gqty-dev/gqty#847]

**Comment by noverby** [comment]
You can use the GQty client directly without react, so yes.

**Comment by PabloSzx** [comment]
some time ago there was work put into an official gqty client for vue, but right now I am not sure what is the status for that




cc @Lappihuan 

> You can use the GQty client directly without react, so yes.

Yes, all the docs of the core-client applies to any JavaScript framework/environment https://gqty.dev/docs/client/fetching-data

**Comment by Lappihuan** [comment]
i'm currently quite busy at work, but i'd love to pick the vue integration up again in a bit.
Iirc it wasn't far away from a functional implementation without the specialized "hooks" like pagination and such.

**Comment by vicary** [comment]
This should be supported via core client. Please reopen if a specific use case is not working, or a vue style data fetching syntax is needed.
