### ISSUE TITLE
RangeError: Maximum call stack size exceeded at deepAssign

### ISSUE THREAD

**Issue by humet** [gqty-dev/gqty#848]
When running this in Next.js I am running into a `Maximum call stack size exceeded` error. It looks like there is some type of endless loop happening. 

The full error is:

```
RangeError: Maximum call stack size exceeded
      at deepAssign (file:///***/node_modules/gqty/Utils/object.mjs:4:20)
      at deepAssign (file://***/node_modules/gqty/Utils/object.mjs:14:44)
at deepAssign (file://***/node_modules/gqty/Utils/object.mjs:14:44)
at deepAssign (file://***/node_modules/gqty/Utils/object.mjs:14:44)
at deepAssign (file://***/node_modules/gqty/Utils/object.mjs:14:44)
at deepAssign (file://***/node_modules/gqty/Utils/object.mjs:14:44)
... and so on
```

When I turn off normalization this doesn't happen. 

Any ideas why this could be? Or what I should start looking at to prevent it?

**Comment by jordanmaslyn** [comment]
@humet There is some ongoing discussion in the next.js repository around a possible issue with Next.JS and Node v16. Can you confirm that you are running Node v16.x? If so, could you try downgrading to Node v14.x and see if the issue goes away?

https://github.com/vercel/next.js/discussions/30785#discussioncomment-1578349 for reference

**Comment by roeean** [comment]
Hi,
I have the same problem, also with Node v14.x

**Comment by vicary** [comment]
@humet Would you please provide a minimum reproducing repo so we can better understand the problem?

**Comment by vicary** [comment]
Please feel free to reopen when you are ready to share more context.

You may also want to try out V3, it is more simplified and powerful!
