### ISSUE TITLE
[Question] GQTy cli uses "gqty.config.js" file for generating pages?

### ISSUE THREAD

**Issue by aitoraznar** [gqty-dev/gqty#850]
Hi.

I have the need to add some headers into the GQTY introspection. 
The command `gqty generate` seems to work fine but when `next build` generates the pages the config it's not used.

so my question is GQTy cli uses "gqty.config.js" file for generating pages?

Many thanks

My config file:
![Screenshot 2022-04-27 at 11 44 53](https://user-images.githubusercontent.com/2470879/165492524-24844f01-95ae-4391-a678-e6b03ed88a00.png)

**Comment by PabloSzx** [comment]
I don't think I understand, gqty doesn't generate any pages, and the whole point of gqty is to only generate once, since all the queries are generated on runtime

**Comment by PabloSzx** [comment]
The config is used on both "gqty generate" and cli programmatic usage https://gqty.dev/docs/cli/programmatic

**Comment by aitoraznar** [comment]
Maybe it's a feature of FaustJS that uses the GraphQL endpoint to get the page data to generate it at NextJS' build time.

I'll try to goo deep into this.

**Comment by vicary** [comment]
If I am understanding the question correctly, `gqty.config.js` is only used when you generate the client.

Common use cases of `next.js` only imports the generated client, it should not be aware of `gqty.config.js` at all.

If you want to include custom headers at runtime, e.g. when you are doing `next build`, you may have to edit the fetch code of the generated client.

**Comment by jordanmaslyn** [comment]
@aitoraznar checkout https://codesandbox.io/s/gqty-sandbox-forked-o9int?from-embed=&file=/src/gqty/index.ts:803-874 as an example of how to provide a custom `queryFetcher` to your gqty client. As mentioned above, the headers in the gqty config are only for the introspection request (which is why they are under the `introspection` property).

**Comment by vicary** [comment]
@aitoraznar please reopen and add more context if you find this is still an issue.
