### ISSUE TITLE
All optional but non-nullable fields throw typescript errors.

### ISSUE THREAD

**Issue by MarkLyck** [gqty-dev/gqty#864]
gqty doesn't seem to generate the correct Typescript types from my graphQL schema.

For example my Query type in graphQL looks like this:

```graphql
type Query implements Node {
  cloudfi: cloudfiQuery
  user: userQuery
  crm: crmQuery
}
```

And a totally valid query that will ALWAYS have a result is:

```graphql
query {
  crm {
    sites({ first: 10 }) {
      id
      name
    }
  }
}
```

But for some when running `gqty generate` it generates this type for Query:

```typescript
export type Maybe<T> = T | null

export interface Query {
  __typename?: 'Query'
  cloudfi?: Maybe<cloudfiQuery>
  crm?: Maybe<crmQuery>
  user?: Maybe<userQuery>
}
```

But that's not correct, while any of the fields are **optional**, none of them are nullable or could ever be null.

This results in constant frustrating typescript errors when using `gqty`.

![Screen Shot 2022-05-18 at 14 15 43](https://user-images.githubusercontent.com/6841110/169116163-afcb2b91-4ad4-40f5-8bd5-b8ee7c0f4752.png)

With the only way to solve the errors (Without disabling them) is to add not 1 unnecessary null insertion operator but 2, for Typescript to be happy that those fields exist.

![Screen Shot 2022-05-18 at 14 26 52](https://user-images.githubusercontent.com/6841110/169117961-6ec051b9-9307-4d00-bcba-ce23c6235218.png)

The point of declaring an optional property or parameter is to make explicit the fact that it might contain no valid value, i.e. null or undefined. Even if the value is tested first, it’s still considered a bad practice to use a non-null assertion like this.

Unless a graphQL type is nullable, gqty should not generate them as `Maybe<T>` types.

The correct exported Query type should just be:

```typescript
export interface Query {
  __typename?: 'Query'
  cloudfi?: cloudfiQuery
  crm?: crmQuery
  user?: userQuery
}
```

**Comment by PabloSzx** [comment]
what do you mean optional but non nullable??

```graphql
type Query implements Node {
  cloudfi: cloudfiQuery
  user: userQuery
  crm: crmQuery
}
```

all those fields are optional and nullable following the graphql spec
