### ISSUE TITLE
GraphQL introspection is not allowed, but the query contained __schema or __type

### ISSUE THREAD

**Issue by sbolinger-godaddy** [gqty-dev/gqty#865]
Hi, thanks for this library. When running yarn generate (for the second time) I get the following error:

`GraphQL introspection is not allowed, but the query contained __schema or __type` and the src/gqty folder is not created.

My graphql API works just fine, I am using WPGraphQL. My gqty.config.cjs file looks like this:

```
/**
 * @type {import("@gqty/cli").GQtyConfig}
 */
const config = {
  react: true,
  scalarTypes: { DateTime: "string" },
  introspection: {
    endpoint: "http://usdhack.com/graphql",
    headers: {},
  },
  destination: "./src/gqty/index.ts",
  subscriptions: false,
  javascriptOutput: false,
};

module.exports = config;
```

Any ideas what went wrong?

**Comment by PabloSzx** [comment]
that's a server-side error, it's most likely missing some headers but it completely depends on the graphql api

**Comment by sbolinger-godaddy** [comment]
My server did not allow public introspection, after enabling the setup worked. Thanks!
