### ISSUE TITLE
Documentation about Suspenсe in React outdated, cuz React 18 is realised

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqty-dev/gqty#904]
https://gqty.dev/docs/react/suspense

**Comment by vicary** [comment]
gqty is not compatible with React 18 yet. We are working on it, contributions are also welcomed.

**Comment by MaxmaxmaximusAWS** [comment]
i'm not talking about gqtt. Im talking about React 18. In your documentation not correct information about React

**Comment by redbar0n** [comment]
@MaxmaxmaximusAWS I'm not a maintainer, but these kinds of changes are fortunately easy to do oneself. I simply scrolled down on the [how to contribute](https://gqty.dev/docs/intro/contributing) page, and found that the docs are under "internal/website/docs", so I browsed the repo, and went [here](https://github.com/gqty-dev/gqty/blob/main/internal/website/docs/react/suspense.mdx), and clicked edit in the upper right corner, edited the text, and  simply followed the steps to create a pull request. Here is the subsequent PR that resolves this issue: https://github.com/gqty-dev/gqty/pull/971

**Comment by PabloSzx** [comment]
closed by https://github.com/gqty-dev/gqty/pull/971 thanks @redbar0n
