### ISSUE TITLE
Allow specifying fetchOptions from Context

### ISSUE THREAD

**Issue by steelbrain** [gqty-dev/gqty#951]
Hello! 👋 

I am working on a GraphQL webapp, written in Next.js where Next.js SSR does the query fetching and then client hydrates the state and continues forward. The GraphQL API server requires authorization, through a simple bearer header. The frontend client does not get access to the authorization details, only the SSR part deals with that.

There's no simply way to do SSR and contextually pass down the `fetchOptions` with GQTY. This leaves us with two choices

- Create a new Client then React Client where the fetcher has been generated with the auth token in context and uses it. This complicates things, as you have to use GQTY from the context everywhere, as having two different instances of it breaks query extraction, so one client during SSR, in components and `getServerSideProps` and the other in client in components
- Create a global state on the server-side that looks a little something like this

<img src="https://user-images.githubusercontent.com/4278113/174547477-ce63598b-be0d-4a14-9b12-6f9f2a2ffacd.png">

The second approach is not concurrency safe, as it means two concurrent executions would fight for control over the global state.

I request that GQTY adds a way to specify `fetchOptions` via context so we can specify it through SSR and leave everything else untouched

**Comment by natew** [comment]
Woah @steelbrain and @PabloSzx in the same place 🤯

**Comment by vicary** [comment]
@steelbrain You may want to try the new [`cachePolicy`](https://gqty.dev/api-reference/react/use-query#cachepolicy) option in V3 😄

I am cleaning up old issues, please feel free to continue the conversation or reopen if you think the new option is not what you wanted.
