### ISSUE TITLE
Prefetching nested objects from array elements

### ISSUE THREAD

**Issue by olabrador** [gqty-dev/gqty#972]
I'd like to know if there's a way to prefetch (as with prepare/prepass) nested objects from objects in an array, resulting in a query similar to this for example:

```
query RootObject($objectId: ID!) {
  RootObject(id: $objectId) {
    nestedArray {
      id
      nestedObject {
        name
      }
    }
  }
}
```

I can't find a way in the documentation with gqty to do this, `prepass` only applies to the first non-null object in the array, `getArrayFields` doesn't do anything with nested objects and `selectFields` just returns an skeleton.

**Comment by donferi** [comment]
Sorry for reviving this but did you figure out a way to do this?
